<a href="https://colab.research.google.com/github/hasanzadekiarash7/learn-tensorflow/blob/main/learns/esentials.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
#how to make arrays with tf(tensorflow)
import tensorflow as tf

In [25]:
# first make to array type(simple and matrix)

# simple
tfarr = tf.constant([1,2,3])
tfarr2 = tf.constant([3,2,1])
# matrix
tfarrmatrix = tf.constant([[1,2,3],[4,5,6],[7,8,9]])
tfarrmatrix2 = tf.constant([[3,2,1],[6,5,4],[9,8,7]])

In [26]:
# make simple operations (+ - * / %)
sumArr = tfarr + tfarr2
minusArr = tfarr - tfarr2
multiplationArr = tfarr * tfarr2
divisionArr = tfarr / tfarr2
remainingArr = tfarr / tfarr2
# for shoing more perfect. at the end use .numpy()
print(sumArr.numpy())
print(minusArr.numpy())
print(multiplationArr.numpy())
print(divisionArr.numpy())
print(remainingArr.numpy())

[4 4 4]
[-2  0  2]
[3 4 3]
[0.33333333 1.         3.        ]
[0.33333333 1.         3.        ]


In [27]:
# make matrix multiplation with matmul tf method(tf.matmul())
mat_mul = tf.matmul(tfarrmatrix, tfarrmatrix2)
print(mat_mul.numpy())

[[ 42  36  30]
 [ 96  81  66]
 [150 126 102]]
